//Fetching data and getting data from each component
export const FETCH_DATA = 'FETCH_DATA';
export const SUBMIT_PART1 = 'SUBMIT_PART1';
export const SUBMIT_PERFORMANCE_TABLE = 'SUBMIT_PERFORMANCE_TABLE';
export const SUBMIT_HABIT_TABLE = 'SUBMIT_HABIT_TABLE';
export const SUBMIT_OTHER_DETAILS = 'SUBMIT_OTHER_DETAILS';
export const SUBMIT_OVERALL = 'SUBMIT_OVERALL';

//Form validations for each stepper
export const SUCCESS_VALIDATION_PART1 = 'SUCCESS_VALIDATION_PART1';
export const FAILURE_VALIDATION_PART1 = 'FAILURE_VALIDATION_PART1';

export const SUCCESS_VALIDATION_PERFORMANCE = 'SUCCESS_VALIDATION_PERFORMANCE';
export const FAILURE_VALIDATION_PERPORMANCE = 'FAILURE_VALIDATION_PERPORMANCE';

export const SUCCESS_VALIDATION_HABIT = 'SUCCESS_VALIDATION_HABIT';
export const FAILURE_VALIDATION_HABIT = 'FAILURE_VALIDATION_HABIT';

export const SUCCESS_VALIDATION_OTHERDETAILS = 'SUCCESS_VALIDATION_OTHERDETAILS';
export const FAILURE_VALIDATION_OTHERDETAILS = 'FAILURE_VALIDATION_OTHERDETAILS';

export const SUCCESS_VALIDATION_OVERALL = 'SUCCESS_VALIDATION_OVERALL';
export const FAILURE_VALIDATION_OVERALL = 'FAILURE_VALIDATION_OVERALL'; 