//export const JNK = "MKM";
export const FETCH_DATA = 'FETCH_DATA';
export const SUBMIT_PART1 = 'SUBMIT_PART1';

//Form validations for each stepper
export const SUCCESS_VALIDATION_PART1 = 'SUCCESS_VALIDATION_PART1';
export const FAILURE_VALIDATION_PART1 = 'FAILURE_VALIDATION_PART1';

export const SUCCESS_VALIDATION_PERFORMANCE = 'SUCCESS_VALIDATION_PERFORMANCE';
export const FAILURE_VALIDATION_PERPORMANCE = 'FAILURE_VALIDATION_PERPORMANCE';

export const SUCCESS_VALIDATION_HABIT = 'SUCCESS_VALIDATION_HABIT';
export const FAILURE_VALIDATION_HABIT = 'FAILURE_VALIDATION_HABIT';

export const SUCCESS_VALIDATION_OTHERDETAILS = 'SUCCESS_VALIDATION_OTHERDETAILS';
export const FAILURE_VALIDATION_OTHERDETAILS = 'FAILURE_VALIDATION_OTHERDETAILS';

export const SUCCESS_VALIDATION_OVERALL = 'SUCCESS_VALIDATION_OVERALL';
export const FAILURE_VALIDATION_OVERALL = 'FAILURE_VALIDATION_OVERALL'; 